# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none
 
parameters:
  - subscription: 'DCD-CNP-PROD'
    service_connection: 'azurerm-prod'
  - subscription: 'DCD-CNP-DEV'
    service_connection: 'azurerm-nonprod'
  - subscription: 'DTS-SHAREDSERVICES-STG'
    service_connection: 'DTS-SHAREDSERVICES-STG'
  - subscription: 'DTS-SHAREDSERVICES-PROD'
    service_connection: 'DTS-SHAREDSERVICES-PROD'

jobs:
  - job: Disable_Resource_locks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Disable resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: ${{ parameters.subscription.service_connection }}
        scriptPath: scripts/disable-resource-locking.sh
        arguments: '$(resource-groups-list)'
