# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none
 
parameters:
  - name: subscriptions
    type: string
    values:
    - 'DCD-CNP-PROD'
    - 'DCD-CNP-DEV'
    - 'DTS-SHAREDSERVICES-STG'
    - 'DTS-SHAREDSERVICES-PROD'

variables:
  - name: DCD-CNP-PROD
    value: 'azurerm-prod'
  - name: DCD-CNP-DEV
    value: 'azurerm-nonprod'
  - name: DTS-SHAREDSERVICES-STG
    value: 'DTS-SHAREDSERVICES-STG'
  - name: DTS-SHAREDSERVICES-PROD
    value: 'DTS-SHAREDSERVICES-PROD'

jobs:
  - job: Disable_Resource_locks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Disable resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: $(${{ parameters.subscription }})
        scriptPath: scripts/disable-resource-locking.sh
        arguments: '$(resource-groups-list)'
