# Docs:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
      - master
# Don't run against PRs
pr: none
 
stages :
- stage: CI
  jobs:
  - job: Disable_Resource_locks
    pool:
      vmImage: 'Ubuntu 16.04'
      timeoutInMinutes: 600
    steps:
    - task: AzureCLI@2
      displayName: 'Disable resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: '$(azureSubscription)'
        scriptPath: scripts/disable-resource-locking.sh
