# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none

schedules:
    - cron: "0 */3 * * *"
      displayName: For Every 3 hours
      branches:
        include:
        - master
      always: true

parameters:
  - name: subscriptions
    type: object
    default:
    - subscription: 'DCD-CNP-PROD'
      service_connection: 'azurerm-prod'
    - subscription: 'DCD-CNP-DEV'
      service_connection: 'azurerm-nonprod'
    - subscription: 'DTS-SHAREDSERVICES-STG'
      service_connection: 'DTS-SHAREDSERVICES-STG'
    - subscription: 'DTS-SHAREDSERVICES-PROD'
      service_connection: 'DTS-SHAREDSERVICES-PROD'

variables:
  - name: DCD-CNP-PROD
    value: 'azurerm-prod'
  - name: DCD-CNP-DEV
    value: 'azurerm-nonprod'
  - name: DTS-SHAREDSERVICES-STG
    value: 'DTS-SHAREDSERVICES-STG'
  - name: DTS-SHAREDSERVICES-PROD
    value: 'DTS-SHAREDSERVICES-PROD'

jobs:
  - job: Enable_Resource_Locks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Enable Resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: $(${{ parameters.subscription }})
        scriptPath: scripts/enable-resource-locking.sh
