# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none

schedules:
    - cron: "0 */3 * * *"
      displayName: For Every 3 hours
      branches:
        include:
        - master
      always: true

jobs:
  - job: Enable_Resource_Locks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Enable Resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: '$(azureSubscription)'
        scriptPath: scripts/enable-resource-locking.sh
