# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none

schedules:
    - cron: "0 */3 * * *"
      displayName: For Every 3 hours
      branches:
        include:
        - master
      always: true

parameters:
  - name: subscriptions
    type: object
    default:
    - stageName: 'CNP_Dev'
      subscription: 'DCD-CNP-DEV'
      serviceConnection: 'azurerm-nonprod'
    - stageName: 'CNP_PROD'
      subscription: 'DCD-CNP-PROD'
      serviceConnection: 'azurerm-prod'
    - stageName: 'SDS_STG'
      subscription: 'DTS-SHAREDSERVICES-STG'
      serviceConnection: 'DTS-SHAREDSERVICES-STG'
    - stageName: 'SDS_PROD'
      subscription: 'DTS-SHAREDSERVICES-PROD'
      serviceConnection: 'DTS-SHAREDSERVICES-PROD'

stages:
  - ${{ each stageName in parameters.subscriptions }}:
    - stage: ${{ stageName.stageName }}
      jobs:
      - job: Enable_Resource_Locks
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: AzureCLI@2
          displayName: 'Enable Resource locks'
          inputs:
            scriptType: bash
            scriptLocation: scriptPath
            azureSubscription: ${{ stageName.serviceConnection }}
            scriptPath: scripts/enable-resource-locking.sh
