# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none

schedules:
    - cron: "0 */3 * * *"
      displayName: For Every 3 hours
      branches:
        include:
        - master
      always: true

stages:
  - stage: Enable_locks
    displayName: Enable locks
    pool: 
      vmImage: ubuntu-latest
    jobs:
    - job: SDS_Prod
      steps:
      - template: run-enable-locks.yaml
        parameters:
          service_connection: DTS-SHAREDSERVICES-PROD
    - job: SDS_STG
      steps:
      - template: run-enable-locks.yaml
        parameters:
          service_connection: DTS-SHAREDSERVICES-STG
    - job: CNP_PROD
      steps:
      - template: run-enable-locks.yaml
        parameters:
          service_connection: azurerm-prod
    - job: CNP_Dev
      steps:
      - template: run-enable-locks.yaml
        parameters:
          service_connection: azurerm-nonprod
